# Generated by Django 3.2.13 on 2022-07-19 08:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220719_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'white'), (2, 'black'), (3, 'red'), (4, 'yelow')], max_length=3, null=True),
        ),
    ]
