# Generated by Django 3.2.13 on 2022-07-19 08:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'white'), (2, 'black'), (3, 'red'), (4, 'yelow')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '37'), (2, '38'), (3, '39'), (4, '40'), (4, '41'), (4, '42'), (4, '43'), (5, '44')], max_length=30, null=True),
        ),
    ]
