# Generated by Django 4.0.5 on 2022-07-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.IntegerField(blank=True, default=300000, null=True),
        ),
    ]
